# Generated by Django 5.0.7 on 2024-07-17 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='emi_due_date',
            field=models.DateField(default=datetime.date(2024, 7, 17)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhar_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
